In [3]:
# import packages
import numpy as np
import pickle

In [5]:
# load data: is "8_encoded_variables" the latest version until now?

# Open the pickle file in binary mode
with open("/workspaces/bakery_sales_prediction/sourcedata/cleaned_data/8_encoded_variables.pkl", 'rb') as f:
    # Load the data from the pickle file
    prepared_data = pickle.load(f)

#data = pd.read_csv("/workspaces/bakery_sales_prediction/sourcedata/cleaned_data/8_encoded_variables.pkl")
#print(data.head(), "\n")

prepared_data.head()

,Umsatz,KielerWoche_1.0,Warengruppe_2.0,Warengruppe_3.0,Warengruppe_4.0,Warengruppe_5.0,Warengruppe_6.0,Feiertage_1.0,Ferientage_1.0,Wetterklasse_2,...,weekday_5,weekday_6,season_2,season_3,season_4,Bewoelkung,Temperatur,Windgeschwindigkeit,Umsatz,Niederschlag
0,148.828353,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,6.0,17.8375,15.0,148.828353,0.3
1,535.856285,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,6.0,17.8375,15.0,535.856285,0.3
2,201.198426,0,0,1,0,0,0,0,1,0,...,0,0,1,0,0,6.0,17.8375,15.0,201.198426,0.3
3,65.890169,0,0,0,1,0,0,0,1,0,...,0,0,1,0,0,6.0,17.8375,15.0,65.890169,0.3
4,317.475875,0,0,0,0,1,0,0,1,0,...,0,0,1,0,0,6.0,17.8375,15.0,317.475875,0.3

In [ ]:
# Selection of Training, Test and Validation data