In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from category_encoders import OneHotEncoder

# Load the dataset
url = "../sourcedata/cleaned_data/6_weather_parameters.csv"
df = pd.read_csv(url)
df

,Datum,Bewoelkung,Temperatur,Windgeschwindigkeit,Wettercode,KielerWoche,Warengruppe,Umsatz,Feiertage,Ferientage,Wetterklasse,Niederschlag,year,month,week,weekday,day_month,season_str,season
0,2013-07-01,6.0,17.8375,15.0,20.0,0.0,1.0,148.828353,0.0,1.0,6,0.3,2013,7,27,0,1,summer,2
1,2013-07-01,6.0,17.8375,15.0,20.0,0.0,2.0,535.856285,0.0,1.0,6,0.3,2013,7,27,0,1,summer,2
2,2013-07-01,6.0,17.8375,15.0,20.0,0.0,3.0,201.198426,0.0,1.0,6,0.3,2013,7,27,0,1,summer,2
3,2013-07-01,6.0,17.8375,15.0,20.0,0.0,4.0,65.890169,0.0,1.0,6,0.3,2013,7,27,0,1,summer,2
4,2013-07-01,6.0,17.8375,15.0,20.0,0.0,5.0,317.475875,0.0,1.0,6,0.3,2013,7,27,0,1,summer,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6994,2018-07-30,6.0,27.7875,10.0,21.0,0.0,1.0,148.541340,0.0,1.0,6,0.0,2018,7,31,0,30,summer,2
6995,2018-07-30,6.0,27.7875,10.0,21.0,0.0,2.0,616.358562,0.0,1.0,6,0.0,2018,7,31,0,30,summer,2
6996,2018-07-30,6.0,27.7875,10.0,21.0,0.0,3.0,348.770346,0.0,1.0,6,0.0,2018,7,31,0,30,summer,2
6997,2018-07-30,6.0,27.7875,10.0,21.0,0.0,4.0,71.822977,0.0,1.0,6,0.0,2018,7,31,0,30,summer,2
6998,2018-07-30,6.0,27.7875,10.0,21.0,0.0,5.0,324.965348,0.0,1.0,6,0.0,2018,7,31,0,30,summer,2

In [5]:
# Defining the column that we want to predict
#X = df.drop('Umsatz', 'Datum', 'Wettercode', 'year', 'month', 'week', 'season_str', axis=1) # Exluding the columns that shall not be included
#y = df['Umsatz']
# Defining the column that we want to predict
X = df.drop(['Umsatz', 'Datum', 'Wettercode', 'year', 'month', 'week', 'season_str'], axis=1) # Excluding the columns that shall not be included
y = df['Umsatz']


# Identify numerical columns and categorical columns
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = X.select_dtypes(include=['object', 'bool']).columns.tolist()

# Exclude weather code from numerical columns
int_or_float_cols_but_categorical = ['Bewoelkung', 'KielerWoche', 'Warengruppe', 'Feiertage', 'Ferientage', 'Wetterklasse', 'weekday', 'day_month', 'season']
numerical_cols = [col for col in numerical_cols if col not in int_or_float_cols_but_categorical]

# Add weather code to categorical columns
categorical_cols.append(int_or_float_cols_but_categorical)

# Initialize the encoder
encoder = OneHotEncoder(cols=categorical_cols)

# Fit and transform the categorical columns
X_encoded = encoder.fit_transform(X)

# Combine the original numerical columns with the encoded categorical columns
X_final = pd.concat([X[numerical_cols], X_encoded], axis=1)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.3, random_state=42)

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
print(f"Mean Squared Error: {mse}")

TypeError: unhashable type: 'list'

In [ ]:
# Assuming 'target' is the column you want to predict
X = df.drop('Umsatz', axis=1)
y = df['Umsatz']

# Identify numerical columns (e.g., prices) and one-hot encode categorical columns
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = X.select_dtypes(include=['object', 'bool']).columns.tolist()

# Initialize the encoder
encoder = OneHotEncoder(cols=categorical_cols)

# Fit and transform the categorical columns
X_encoded = encoder.fit_transform(X[categorical_cols])

# Combine the original numerical columns with the encoded categorical columns
X_final = pd.concat([X[numerical_cols], X_encoded], axis=1)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.2, random_state=42)

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
print(f"Mean Squared Error: {mse}")